export const LANG_EN_NAME = 'en-US';
export const LANG_EN_TRANS = {

  'analytics.ad.pointer.reports': 'Reports',
  'analytics.ad.pointer.charts': 'Charts',
  'analytics.ad.pointer.ads': 'Ads',
  'analytics.ad.pointer.brands': 'Brands',
  'analytics.ad.pointer.company': 'Company',
  'analytics.ad.pointer.industry': 'Industry',
  'analytics.ad.pointer.numberofads':'Number of Ads',
  'analytics.required.field':'Required Field',
  'analytics.user.is.null.or.empty':'The user is null or empty',
  'analytics.startdate.required.field':'Start date required field',
  'analytics.enddate.required.field':'End date required field',
  'analytics.percentage.of.top.ads':'Percentage of top 10 ads',
  'analytics.number.of.ads.by.channel':'Number of ads by chanel',
  'analytics.ad.pointer.drive.to.web':'Drive to web',
  'analytics.ad.pointer.web.site.reach':'Web site reach',
  'analytics.number.of.brands.by.channel':'Number od brands by chanal',
  'analytics.ad.pointer.facebook.page.view':'Facebook Page Reach',
  'analytics.ad.pointer.youtube.view':'Youtube Reach',
  'analytics.ad.pointer.instagram.profile.view':'Instagram Page Reach',
  'analytics.ad.pointer.btn.generate': 'Generate',
  'analytics.ad.pointer.drive.to.web.page.reach': 'Page Reach',
  'analytics.number.of.companies.by.channel':'Number of companies by channel',
  'analytics.number.of.industries.by.channel':'Number of industries by channel',
  'analytics.ad.pointer.linkedin.followers':'LinkedIn Followers',
  'analytics.ad.pointer.twitter.followers':'Twitter Followers',
  'analytics.ad.pointer.numberofbrands' :'Number of Brands',
  'analytics.percentage.of.top.brands':'Percentage of top 10 brands',
  'analytics.ad.pointer.numberofcompanies' :'Number of Companies',
  'analytics.percentage.of.top.companies' : 'Percentage of top 10 companies',
  'analytics.ad.pointer.numberofindustries':'Number of Industries',
  'analytics.percentage.of.top.industries':'Percentage of top 10 industries'
};

