version: '3.4'

services:
  analytics.microservice:
    image: analyticsmicroservice:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Analytics.Microservice"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_analytics.microservice$
    volumes:
      - C:\Projects\DriveToWeb\DEV\Microservices\Analytics\Analytics.Microservice:/app
      - C:\Projects\DriveToWeb\DEV:/src
      - C:\Users\aleksandar.dicoski\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_analytics.microservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_analytics.microservice$ \"/app/bin/Debug/net5.0/Analytics.Microservice.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true